Added docs on how to self host logviewer (and the patreon version)
modmail-dev/modmail-docs pull request #18
Opened 2023-03-30 14:07 UTC by sebkuip

Also has lots of images :)

2023-03-30 14:08 UTC, CrowAndBoots approved these changes

2023-03-30 14:09 UTC, CrowAndBoots submitted a review, later dismissed

2023-03-30 14:16 UTC, CrowAndBoots approved these changes

2023-03-30 16:01 UTC, StephenDaDev requested changes

2023-03-30 16:01 UTC, StephenDaDev commented on installation/local-hosting-vps/logviewer.md
> +Then save the file and exit nano by pressing `ctrl + x`, then `y` and `enter`.
view above

2023-03-30 16:01 UTC, StephenDaDev commented
It should also be merged into development not main

2023-03-31 22:47 UTC, sebkuip commented on installation/local-hosting-vps/logviewer.md
> +git clone https://github.com/modmail-dev/logviewer logviewer
Taken from the original logviewer guide to ensure the filename is correct (i assume that git will automatically try to resolve name errors by renaming, this should force the name)

2023-03-31 22:47 UTC, sebkuip commented on installation/local-hosting-vps/logviewer.md
> +* You must have git installed on your system. If you do not, run `sudo apt install git` to install it.
It states above that it's assuming Ubuntu

2023-03-31 23:34 UTC, StephenDaDev requested changes
Still aimed at wrong branch

2023-03-31 23:34 UTC, StephenDaDev commented on installation/local-hosting-vps/patreon_logviewer.md
> +First, copy the Client ID and Client Secret. You will need these later when filling in the .env.
So far we have been referring to file names as `inline code`. Probably should change for consistency

2023-03-31 23:34 UTC, StephenDaDev commented on installation/local-hosting-vps/patreon_logviewer.md
> +To configure the .env file, you can use the following command:
same as above

2023-03-31 23:34 UTC, StephenDaDev commented on installation/local-hosting-vps/patreon_logviewer.md
> +This will copy the example .env file and open it in nano. You can then edit the file with your info. Besides the normal logviewer config, you will also need to add your bot's token and the client ID
Wouldn't they need to open `.env.example` not `.env`?

2023-03-31 23:34 UTC, StephenDaDev commented on installation/local-hosting-vps/patreon_logviewer.md
> +`oauth whitelist roleID` or `oauth whitelist userID`.
We are going to use the `?` prefix when providing example commands

2023-04-01 03:55 UTC, Zinoviya99 approved these changes

2023-04-10 21:35 UTC, StephenDaDev approved these changes
Looks good to me

2023-04-11 02:36 UTC, merged